# User Service Canary Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrapzee-ingress-user-canary
  namespace: scrapzee
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: scrapzee.local
    http:
      paths:
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-service-canary
            port:
              number: 80

