# Auth Service Canary Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrapzee-ingress-auth-canary
  namespace: scrapzee
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service-canary
            port:
              number: 80